//! Cross-language vectors for the two algorithms an SDK cannot get subtly wrong.
//!
//! `step_hash` and the request signature are where a second implementation can
//! disagree with this one and have both look correct. A step hash differing by
//! one byte errors nowhere: the server holds a result the handler never asks
//! for, the handler asks for one the server does not have, the step re-executes,
//! and the run completes green. A wrong signature is at least loud, but only
//! against a server — an SDK's own tests would happily agree with themselves.
//!
//! So the vectors live in `spec/fixtures/protocol.json`, beside the
//! specification rather than inside either implementation, and every language
//! binding asserts against that one file. This test is the Rust half.
//!
//! Regenerate with `STEPD_REGENERATE_FIXTURES=1 cargo test -p stepd-proto --test
//! fixtures`, and only when adding cases. A regeneration that changes an
//! existing vector is either a protocol change or a defect; committing it
//! quietly would let every other binding be "corrected" to match a bug.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Serialize, Deserialize)]
struct Fixtures {
    note: String,
    step_hash: Vec<HashCase>,
    signature: Vec<SigCase>,
}

#[derive(Serialize, Deserialize)]
struct HashCase {
    why: String,
    function_id: String,
    step_id: String,
    occurrence: u32,
    hash: String,
}

#[derive(Serialize, Deserialize)]
struct SigCase {
    why: String,
    key: String,
    body: String,
    timestamp: i64,
    nonce: String,
    header: String,
}

fn path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../fixtures/protocol.json")
}

const LONG_KEY: &str =
    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

/// The inputs. Every output is computed, so a case cannot be written to match a bug.
fn hash_inputs() -> Vec<(&'static str, &'static str, &'static str, u32)> {
    vec![
        ("the ordinary case", "order-fulfilment", "charge", 0),
        (
            "occurrence is part of identity",
            "order-fulfilment",
            "charge",
            1,
        ),
        ("and keeps counting", "order-fulfilment", "charge", 2),
        (
            "a child function cannot collide with its parent's step",
            "refunds/issue",
            "charge",
            0,
        ),
        (
            "the 0x1F separator is why this differs from the next case",
            "a",
            "bc",
            0,
        ),
        (
            "plain concatenation would make these two identical",
            "ab",
            "c",
            0,
        ),
        (
            "occurrence is decimal text, not a fixed-width field",
            "f",
            "s",
            10,
        ),
        ("so 100 must not hash as 1 followed by 00", "f", "s", 100),
        ("well past the 10 000-step ceiling", "f", "s", 99999),
        (
            "non-ASCII ids hash over their UTF-8 bytes",
            "facturación",
            "café-☕",
            0,
        ),
        (
            "an id containing the dot the signature format also uses",
            "f",
            "step.with.dots",
            0,
        ),
        ("the common fan-out shape", "billing", "charge-4711", 7),
    ]
}

fn sig_inputs() -> Vec<(&'static str, &'static str, &'static str, i64, &'static str)> {
    vec![
        (
            "the ordinary case",
            "stepd-conformance",
            r#"{"protocol":"1","ops":[]}"#,
            1_700_000_000,
            "n0",
        ),
        (
            "an empty body still signs",
            "stepd-conformance",
            "",
            1_700_000_000,
            "n1",
        ),
        (
            "the body is signed verbatim, dots and all",
            "k",
            "a.b.c",
            0,
            "n2",
        ),
        ("newlines survive", "k", "line1\nline2", 42, "n3"),
        (
            "non-ASCII bodies sign over UTF-8 bytes",
            "k",
            r#"{"who":"café ☕"}"#,
            1,
            "n4",
        ),
        (
            "a key longer than the block is hashed down, not truncated",
            LONG_KEY,
            "{}",
            7,
            "n5",
        ),
        ("a short key is padded, not rejected", "k", "{}", 8, "n6"),
        ("timestamp 0 is a value, not absence", "k", "{}", 0, "n7"),
    ]
}

fn generate() -> Fixtures {
    Fixtures {
        note: "Generated by spec/rust/crates/stepd-proto/tests/fixtures.rs. Every language \
               binding of PROTOCOL.md asserts against this file, so the two algorithms an SDK \
               can get subtly and silently wrong are checked against one artefact instead of \
               against each implementation's own idea of them. See §6 and §9."
            .into(),
        step_hash: hash_inputs()
            .into_iter()
            .map(|(why, f, s, n)| HashCase {
                why: why.into(),
                function_id: f.into(),
                step_id: s.into(),
                occurrence: n,
                hash: stepd_proto::step_hash(f, s, n),
            })
            .collect(),
        signature: sig_inputs()
            .into_iter()
            .map(|(why, key, body, ts, nonce)| SigCase {
                why: why.into(),
                key: key.into(),
                body: body.into(),
                timestamp: ts,
                nonce: nonce.into(),
                header: stepd_proto::sign(key.as_bytes(), body, ts, nonce),
            })
            .collect(),
    }
}

#[test]
fn the_committed_fixtures_are_what_this_crate_produces() {
    let generated = generate();

    if std::env::var("STEPD_REGENERATE_FIXTURES").is_ok() {
        let mut json = serde_json::to_string_pretty(&generated).unwrap();
        json.push('\n');
        std::fs::write(path(), json).expect("could not write the fixtures");
        eprintln!("regenerated {}", path().display());
        return;
    }

    let raw = std::fs::read_to_string(path()).unwrap_or_else(|e| {
        panic!(
            "could not read {}: {e}. Generate it with STEPD_REGENERATE_FIXTURES=1 \
             cargo test -p stepd-proto --test fixtures",
            path().display()
        )
    });
    let committed: Fixtures = serde_json::from_str(&raw).expect("the fixtures did not parse");

    assert_eq!(
        committed.step_hash.len(),
        generated.step_hash.len(),
        "the committed file has a different number of hash cases than this test builds"
    );
    for (c, g) in committed.step_hash.iter().zip(&generated.step_hash) {
        assert_eq!(
            (&c.function_id, &c.step_id, c.occurrence),
            (&g.function_id, &g.step_id, g.occurrence),
            "the committed cases are in a different order than this test builds them"
        );
        assert_eq!(
            c.hash, g.hash,
            "step_hash({:?}, {:?}, {}) changed — every other language binding is now wrong, \
             and so is every run in flight",
            c.function_id, c.step_id, c.occurrence
        );
    }

    assert_eq!(
        committed.signature.len(),
        generated.signature.len(),
        "the committed file has a different number of signature cases than this test builds"
    );
    for (c, g) in committed.signature.iter().zip(&generated.signature) {
        assert_eq!(
            (&c.key, &c.body, c.timestamp, &c.nonce),
            (&g.key, &g.body, g.timestamp, &g.nonce),
            "the committed cases are in a different order than this test builds them"
        );
        assert_eq!(
            c.header, g.header,
            "the signature for body {:?} at {} changed",
            c.body, c.timestamp
        );
    }
}

#[test]
fn the_fixtures_actually_discriminate() {
    // Two of the vectors exist to prove the 0x1F separator does something. If
    // they ever agree, that pair has stopped testing anything — and the property
    // it guards, that ("a","bc") and ("ab","c") cannot collide, is the whole
    // reason the separator is in the algorithm.
    assert_ne!(
        stepd_proto::step_hash("a", "bc", 0),
        stepd_proto::step_hash("ab", "c", 0),
        "the separator is not doing its job"
    );
    assert_ne!(
        stepd_proto::step_hash("f", "s", 10),
        stepd_proto::step_hash("f", "s", 100),
        "occurrence is being concatenated without a boundary"
    );
}
